// Replace with your request types
export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_BANNERS_REQUEST = 'GET_BANNERS_REQUEST';
export const GET_DATA_REQUEST_SUCCESS = 'GET_DATA_REQUEST_SUCCESS';
export const ADD_REMOVE_TO_CART_REQUEST = 'ADD_REMOVE_TO_CART_REQUEST';
export const ADD_SELECTED_KEY_REQUEST = 'ADD_SELECTED_KEY_REQUEST';
